version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/mydb

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simplenodeapp
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb 
      - PORT=3000

volumes:
  mongo_data:
